[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.10"
diesel={ version = "1.4.4", features = ["mysql"] }
dotenv = "0.15.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
bcrypt="0.10"
rand = "0.8"

[dependencies.rocket_contrib]
version="0.4.10"
default-features = false
features = ["json"]
